<?php
/**
* HANKEME
*
* NOTICE OF LICENSE
*
* This source file is exclusively published under the Open Software License (OSL 3.0)
* See http://opensource.org/licenses/osl-3.0.php for Details
* In case of questions regarding the use of this source file please
refer to the contact below.
*
* @project: [HANKEME Chameleon]
* @contact: info@hankeme.de
* @collaborators: [strohmeier]
*/
?>
<?php if ($this->getFilesCount() > 0): ?>
<ul class="fileslist">
    <?php foreach ($this->getFiles() as $file): ?>
    <li>
	    <div class="filecnt chameleon-type-<?php echo $this->getFileType($file);?>" id="<?php echo $this->getFileId($file) ?>"></div>
		<small><?php echo $this->getFileName($file);  ?></small>
    </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
    <?php echo $this->helper('cms')->__('No files found') ?>
<?php endif; ?>
